[project]
name = "crc-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "kaleido>=0.2.1",
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "crc-sdk[zarr,raster,geometry]>=0.1.0",
]

# temp source until crc-sdk is published to PyPI
[tool.uv.sources]
crc-sdk = { git = "ssh://git@github.com/RiskThinking/crc-sdk.git", branch = "geotiff" }
